# Generated by Django 5.1.7 on 2025-06-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción breve')),
            ],
        ),
    ]
