# Generated by Django 5.1.7 on 2025-06-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='¿Está disponible?'),
        ),
    ]
