# Generated by Django 5.1.7 on 2025-11-06 02:12

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfil_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nit_empresa', models.CharField(default='900123456-1', max_length=20)),
                ('nombre_empresa', models.CharField(default='Lacteos Aqui Es Purita', max_length=100)),
                ('direccion_empresa', models.CharField(default='cra 12 #34-56, La Cumbre Valle Del Cauca', max_length=150)),
                ('correo_empresa', models.EmailField(default='lacteospurita@gmail.com', max_length=254)),
                ('telefono_empresa', models.CharField(default='+57 3000000000', max_length=20)),
                ('resolucion_dian', models.CharField(default='18760000000000', max_length=50)),
                ('prefijo_factura', models.CharField(default='LP', max_length=10)),
                ('forma_pago', models.CharField(default='Contado', max_length=50)),
                ('medio_pago', models.CharField(default='Efectivo', max_length=50)),
                ('cufe', models.CharField(default=core.models.generar_cufe, max_length=64, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.producto')),
            ],
        ),
    ]
