# Generated by Django 5.1.7 on 2025-11-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
