# Generated by Django 5.1.7 on 2025-11-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
