# Generated by Django 5.1.7 on 2025-11-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auditoria_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='detalles',
        ),
    ]
