# Generated by Django 5.1.7 on 2025-11-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_auditoria_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
